# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: 'Default'
  demands:
    Agent.Name -equals Hriday Azure Agent

steps:
- bash: ./svc.sh start
- task: JavaToolInstaller@0
  displayName: 'Use Java 21'
  inputs:
    versionSpec: '21'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'LocalDirectory'
    jdkFile: '/Users/mr.heart_2711/Desktop/Azure Agent/Agent/jdk-21_macos-x64_bin.tar.gz'
    jdkDestinationDirectory: '/Users/mr.heart_2711/Desktop/Azure Agent/Agent/externals/java21'
    cleanDestinationDirectory: true
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean install'
- bash: ./svc.sh stop

