# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: "20"
    jdkArchitectureOption: x64
    jdkSourceOption: LocalDirectory
    jdkFile: "/Users/mr.heart_2711/Desktop/Azure Agent/Agent/JDK/openjdk-20.0.1_macos-x64_bin.tar.gz"
    jdkDestinationDirectory: "/Users/mr.heart_2711/Desktop/Azure Agent/Agent/JDK/"
    cleanDestinationDirectory: true

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean install test'
